SQLALCHEMY_DATABASE_URI = "mysql+pymysql://td:LNWRcTyWEb9XF2cS@129.242.219.41/td"

SECRET_KEY = "SUPER SECRET KEY THAT NO ONE CAN FIND"
CSRF_ENABLED = True
USER_ENABLE_EMAIL = True

SQLALCHEMY_POOL_RECYCLE = 60
SQLALCHEMY_ECHO = True

#SERVER_NAME = "dataforeninga.org"