SQLALCHEMY_DATABASE_URI = "mysql://td:AEmsEmyQyj4zWE2N@129.242.219.41/TD"

SECRET_KEY = "SUPER SECRET KEY THAT NO ONE CAN FIND"
CSRF_ENABLED = True
USER_ENABLE_EMAIL = True

SQLALCHEMY_POOL_RECYCLE = 60
SQLALCHEMY_ECHO = True